### ISSUE TITLE
BUG? when starting the server up

### ISSUE THREAD

**Issue by 1arrcy1** [Didstopia/rust-server#91] opened 2021-01-15 22:49 UTC
used information on https://rust.didscraft.com/rust-server-on-linux-using-docker/

input:
`docker run --restart always -it --name rust-server -d -p 28015:28015 -p 28015:28015/udp -p 28016:28016 -p 8080:8080 -v /home/race/datastore/rust/world:/steamcmd/rust --env-file /home/race/datastore/rust/rust-config/rust.env didstopia/rust-server`

config:

```
RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load -logfile /dev/stdout +server.secure 1
RUST_SERVER_IDENTITY=my_awesome_server
RUST_SERVER_SEED=12345
RUST_SERVER_NAME=My Awesome Server
RUST_SERVER_DESCRIPTION=This is my awesome server
RUST_RCON_PASSWORD=SuperSecurePassword
```

output:
` Update state (0x5) verifying install, progress: 91.93 (3933982021 / 4279425080)

 Update state (0x5) verifying install, progress: 94.12 (4027693680 / 4279425080)

 Update state (0x5) verifying install, progress: 96.96 (4149386651 / 4279425080)

 Update state (0x5) verifying install, progress: 99.43 (4255233344 / 4279425080)

Success! App '258550' fully installed.

quit

Starting web server..

Log rotation disabled!

Disabling internal stdout/stderr logging!

Starting Rust..

Found path: /steamcmd/rust/RustDedicated

Unable to open log file, exiting.

Exiting..`

**Comment by s3cpat** [comment] 2021-01-18 19:54
Looks like a duplicate of #88 

> Facepunch updated Rust to use a newer version of Unity, which ones again broke existing linux compatibility, including stdoud/stderr support. This is why the image no longer uses `-logfile /dev/stdout` by default.

https://github.com/Didstopia/rust-server/issues/88#issuecomment-752016822

**Closed** 2021-05-20 12:11 UTC
Labels: wontfix
